#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [_QWERTY] = LAYOUT(KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9,
                 KC_0, KC_GRV, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U,
                 KC_I, KC_O, KC_P, KC_MINS, KC_LSFT, KC_A, KC_S, KC_D, KC_F,
                 KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_BSLS, KC_LCTL, KC_Z,
                 KC_X, KC_C, KC_V, KC_B, KC_LBRC, KC_RBRC, KC_N, KC_M, KC_COMM,
                 KC_DOT, KC_SLSH, KC_EQL, KC_LALT, KC_LGUI, MO(1), KC_SPC,
                 KC_ENT, MO(1), KC_BSPC, KC_RGUI),
    [_RAISE] = LAYOUT(KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9,
                 KC_F10, KC_F11, KC_F12, KC_NO, KC_NO, KC_UP, KC_NO, KC_NO,
                 KC_NO, KC_MSTP, KC_MPRV, KC_MPLY, KC_MNXT, KC_NO, KC_VOLU,
                 KC_LSFT, KC_LEFT, KC_DOWN, KC_RGHT, KC_NO, KC_NO, KC_LEFT,
                 KC_DOWN, KC_UP, KC_RGHT, KC_NO, KC_VOLD, KC_LCTL, KC_NO,
                 KC_CUT, KC_COPY, KC_PSTE, KC_NO, KC_DQUO, KC_QUOT, KC_NO,
                 KC_NO, KC_NO, KC_NO, KC_NO, KC_RSFT, KC_NO, KC_NO, KC_NO,
                 KC_NO, KC_NO, KC_NO, KC_NO, KC_NO)};
