#! /bin/sh
# in order to reload the config, just execute the script again

eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh) export SSH_AUTH_SOCK

# caps is a useless key
# change it into a useful key
setxkbmap -option caps:escape
setxkbmap -layout us -variant altgr-intl

killall -q sxhkd
while pgrep -u $UID -x sxhkd >/dev/null; do sleep 1; done
sxhkd &

if [[ "$HOSTNAME" == "dell-xps" ]]; then
	xrandr --output eDP1 --mode 1920x1080 --dpi 96 --scale 1.0x1.0
	if [[ $(xrandr | grep "HDMI1 connected") ]]; then
		# --same-as
		# --above
		# --below
		# --left-of
		# --right-of
		xrandr --output HDMI1 --mode 1920x1080 --dpi 96 --scale 1.0x1.0 --same-as eDP1
	fi
else
	echo "Set the resolution!"
fi

xsetroot -cursor_name left_ptr &

# picom
killall -q picom
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
picom &

killall -q xbanish
while pgrep -u $UID -x xbanish >/dev/null; do sleep 1; done
xbanish &

if [[ "$HOSTNAME" == "dell-xps" ]]; then
	bspc monitor eDP1 -d 1 2 3 4 5
	if [[ $(xrandr | grep "HDMI1 connected") ]]; then
		bspc monitor HDMI1 -d 6 7 8 9 10
	fi

elif [[ "$HOSTNAME" == "shootingstar" ]]; then
	bspc monitor DP-1 -d 1 2 3 4 5 101 102
	bspc monitor DP-5 -d 6 7 8 9 10 102 103
	# bspc monitor HDMI-0 -d X Y Z
fi

bspc config top_padding 34

if [[ "$HOSTNAME" == "shootingstar" ]]; then
	bspc config -m DP-1 bottom_padding 34
elif [[ "$HOSTNAME" == "dell-xps" ]]; then
	bspc config bottom_padding 34
fi

bspc config border_width 4
bspc config window_gap 14
bspc config split_ratio 0.52
bspc config borderless_monocle false
bspc config gapless_monocle false

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
bspc config focus_follows_pointer true

if [[ "$HOSTNAME" == "dell-xps" ]]; then
	xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Natural Scrolling Enabled" 1
	xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Click Method Enabled" 0 1
	xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Tapping Enabled" 1
elif [[ "$HOSTNAME" == "shootingstar" ]]; then
	# Map wacom only to primary screen
	# https://tonisagrista.com/blog/2021/map-wacom-one-screen/
	for item in $(xinput | grep Wacom | grep pointer | grep -oP 'id=\K\d+' | xargs); do
		xinput map-to-output $item $(xrandr | grep primary | cut -d " " -f 1 | xargs)
	done
fi

bspc config external_rules_command "$HOME/.config/bspwm/external-rules"

# wallpaper
$HOME/.config/wallpaper.sh
sleep 1.0

# dunst
$HOME/.config/dunst/launchdunst.sh

killall -q ntfd
while pgrep -u $UID -x ntfd >/dev/null; do sleep 1; done

OWM_API_KEY="$(pass openweathermap.org/api_keys/ntfd)" ntfd &

# polybar
$HOME/.config/polybar/scripts/launch.sh

# Launch gammastep
systemctl --user start gammastep

# Launch xautolock
systemctl --user start xautolock
