#! /bin/sh
# in order to reload the config, just execute the script again

eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh) export SSH_AUTH_SOCK

# caps is a useless key
# change it into a useful key
setxkbmap -option caps:escape
setxkbmap -layout us -variant altgr-intl

pkill sxhkd
sxhkd &

if [[ "$HOSTNAME" == "dell-xps" ]]; then
	xrandr --output eDP1 --mode 1920x1080 --dpi 96 --scale 1.0x1.0
else
	echo "Set the resolution!"
fi

xsetroot -cursor_name left_ptr &

# picom
pkill picom
picom &

pkill xbanish
xbanish &

pkill xautolock
xautolock -time 5 -locker noxlock &

if [[ "$HOSTNAME" == "dell-xps" ]]; then
    bspc monitor -d 1 2 3 4 5
elif [[ "$HOSTNAME" == "shootingstar" ]]; then
    bspc monitor DP-1 -d 1 2 3 4 5
	bspc monitor DP-5 -d 6 7 8 9 10
	bspc monitor HDMI-0 -d X
fi

bspc config top_padding 36
bspc config border_width		4
bspc config window_gap			14
bspc config split_ratio			0.52
bspc config borderless_monocle	false
bspc config gapless_monocle		false

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
bspc config focus_follows_pointer true

if [[ "$HOSTNAME" == "dell-xps" ]]; then
    xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Natural Scrolling Enabled" 1
    xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Click Method Enabled" 0 1
    xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Tapping Enabled" 1
fi

bspc config external_rules_command "$HOME/.config/bspwm/external-rules"

# wallpaper
$HOME/.config/wallpaper.sh &

sleep 0.5

# dunst
$HOME/.config/dunst/launchdunst.sh

# polybar
$HOME/.config/polybar/scripts/launch.sh
